### ISSUE TITLE
[BUG] email white list

### ISSUE THREAD

**Issue by Hansanghyeon** [Hansanghyeon/synology-traefik#3]
https://github.com/thomseddon/traefik-forward-auth/blob/master/README.md#user-restriction

해당 방식대로

```yaml

  fauth:
    container_name: fauth
    image: thomseddon/traefik-forward-auth:2.2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} # REDACTED
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_ID} # REDACTED
      - SECRET=${OAUTH_SECRET}
      - INSECURE_COOKIE=false
      - WHITELIST=dandan9509@gmail.com
```

이런 식으로 구현해도 white list가 재대로 구현되지 않는 것을 볼 수 있다.

docker logs로 해당 컨테이너에 인증된 부분을 보면 로그로 이렇게 나온다.
`msg="Invalid email" email=`
